---
- hosts: nursery-pi
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
  - name: Update
    apt: uprade=dist update_cache=yes
  - name: Install some extra packages
    apt: name={{ item }} state=latest
    with_items:
      - vim
      - vlc
      - python3-picamera
